import Head from "next/head";
import Feed from "../components/Feed";
import Modal from "../components/Modal";
import Sidebar from "../components/Sidebar";
import Widget from "../components/Widget";
import styles from "../styles/Home.module.css";

export default function Home({ newsResults }) {
  return (
    <div>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* sidebar */}
        <Sidebar />

        {/* feed */}
        <Feed />

        {/* widgets */}
        <Widget newsResults={newsResults.articles} />

        {/* modal */}
        {/* <Modal /> */}
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/in.json"
  ).then((res) => res.json());
  return {
    props: {
      newsResults,
    },
  };
}
